name: Verificação de Código

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verificar:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar repositório
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # ou a versão do Node.js que você usa

    - name: Instalar dependências
      run: npm install

    - name: Rodar testes
      run: node test.js  # Aqui estamos executando o arquivo de teste diretamente
